FROM python:3

WORKDIR /poll

COPY . .

RUN pip install -r requirements.txt

EXPOSE 80

CMD ["flask","run","--host=0.0.0.0","--port=80"]

# docker build -t poll .  
# docker run -p 80:80 poll                                                                                                         